---
title: "RAGNAR PV - KM Plots"
author: "Preliminary Document"
date: "Date prepared `r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - usepackage{draftwatermark}
output:
  html_document:
    css: "style.css"
    df_print: paged
    theme: yeti
pdf_document:
  number_sections: yes
  toc: yes
---
```{r, include=FALSE}
## Import data
library(readxl)
library(dplyr)
library(tidyr)
library(kableExtra)
library(ggplot2)
library(survminer)
library(dplyr)
library(tidyr)
library(tidyverse)
library(readxl)
library(survival)
library(ggpmisc)
library(ggforce)
library(janitor)

## Set options for Plot size
knitr::opts_chunk$set(fig.width=20, fig.height=8) 

## Import and Run data
setwd('C:\\Users\\matthew.baranoff\\Working\\ragNAR')
rag_clean <-  read.csv('analytic_cohort.csv')
rag <- rag_clean

rag$Patient.Characteristic...Disease.[which(rag$Patient.Characteristic...Disease. == 'nsclc')] <- 
  'non small cell lung cancer (nsclc)' 
rag$Patient.Characteristic...Disease.[which(rag$Patient.Characteristic...Disease. == 'crc')]  <- 'Colorectal Cancer (CRC)'
rag$Patient.Characteristic...Disease.[which(rag$Patient.Characteristic...Disease. == 'adv_cca')] <- 
  'Advanced Cholangiocarcinoma (advcca)' 

```

# All Data

```{r echo = FALSE, warning=FALSE, message=FALSE}
setwd('C:\\Users\\matthew.baranoff\\Working\\RAGNAR\\Tools')
load('RagnarOutcome.RData')

Pan_Specific_analysis <- RagnarOutcomes(rag,"All_Data_")
ggarrange(Pan_Specific_analysis$No_DelayAll_Data_, Pan_Specific_analysis$With_DelayAll_Data_)

```

# Flatiron Universal Data Model (UDM)

```{r echo = FALSE, warning=FALSE, message=FALSE}
Pan_Specific_analysis <- RagnarOutcomes(rag[which(rag$Patient.Characteristic..Pan.tumor.pt..),],"Flatiron_Universal_Data_Model_")
ggarrange(Pan_Specific_analysis$No_DelayFlatiron_Universal_Data_Model_, Pan_Specific_analysis$With_DelayFlatiron_Universal_Data_Model_)
```

# Foundation Medicine’s Clinico-Genomic Database (CG Database)

```{r echo = FALSE, warning=FALSE, message=FALSE}
Pan_Specific_analysis <- RagnarOutcomes(rag[which(rag$Patient.Characteristic..Tumor.specific.pt.),],"Foundation_Medicines_Clinico_Genomic_Database_")
ggarrange(Pan_Specific_analysis$No_DelayFoundation_Medicines_Clinico_Genomic_Database_, Pan_Specific_analysis$With_DelayFoundation_Medicines_Clinico_Genomic_Database_)

```

# By Tumor

```{r echo = FALSE, warning=FALSE, message=FALSE, results = 'asis'}
## Run Over all Tumor Types

for(k in unique(rag$Patient.Characteristic...Disease.)) {
  
  ## Create variable that contains the data for the tumor of the current interation
  temp_rag <- rag[which(rag$Patient.Characteristic...Disease. == k),]
  
  ## Selection tumor that have more than > 10 obs for both FGFR status
  if (all(table(temp_rag$Patient.Characteristic...FGFR.Status.) > 10)) {
      cat('\n\n## Tumor: `', toupper(k), '`\n\n')
    Pan_Specific_analysis <- RagnarOutcomes(temp_rag,paste0(toupper(k), ' '))
    print(
      ggarrange(Pan_Specific_analysis[[7]], Pan_Specific_analysis[[8]], ncol = 2)
    )
  }
}

```


